### ISSUE TITLE
android.content.res.Resources$NotFoundException: File res/drawable-v21/launch_background.xml 

### ISSUE THREAD

**Issue by Megidd** [flutter/gallery#383]
**Describe the bug**

Previously I was building and running fine. I don't remember making any change, but recently, I run into such errors while building and running the app on a Samsung Galaxy Note 3 through Android Studio:

```bash
Launching lib\main.dart on SM N900 in debug mode...
Running Gradle task 'assembleDebug'...
E/AndroidRuntime(12731): FATAL EXCEPTION: main
E/AndroidRuntime(12731): Process: io.flutter.demo.gallery, PID: 12731
E/AndroidRuntime(12731): java.lang.RuntimeException: Unable to start activity ComponentInfo{io.flutter.demo.gallery/io.flutter.demo.gallery.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable-v21/launch_background.xml from drawable resource ID #0x7f040000
E/AndroidRuntime(12731): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
E/AndroidRuntime(12731): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
E/AndroidRuntime(12731): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)
E/AndroidRuntime(12731): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
E/AndroidRuntime(12731): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(12731): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(12731): 	at android.app.ActivityThread.main(ActivityThread.java:5942)
E/AndroidRuntime(12731): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12731): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(12731): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
E/AndroidRuntime(12731): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
E/AndroidRuntime(12731): Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v21/launch_background.xml from drawable resource ID #0x7f040000
E/AndroidRuntime(12731): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3752)
E/AndroidRuntime(12731): 	at android.content.res.Resources.loadDrawable(Resources.java:3620)
E/AndroidRuntime(12731): 	at android.content.res.Resources.getDrawable(Resources.java:1852)
E/AndroidRuntime(12731): 	at android.content.res.Resources.getDrawable(Resources.java:1818)
E/AndroidRuntime(12731): 	at io.flutter.embedding.android.FlutterActivity.getSplashScreenFromManifest(FlutterActivity.java:495)
E/AndroidRuntime(12731): 	at io.flutter.embedding.android.FlutterActivity.provideSplashScreen(FlutterActivity.java:469)
E/AndroidRuntime(12731): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:301)
E/AndroidRuntime(12731): 	at io.flutter.embedding.android.FlutterActivity.createFlutterView(FlutterActivity.java:520)
E/AndroidRuntime(12731): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:414)
E/AndroidRuntime(12731): 	at android.app.Activity.performCreate(Activity.java:6283)
E/AndroidRuntime(12731): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
E/AndroidRuntime(12731): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
E/AndroidRuntime(12731): 	... 10 more
E/AndroidRuntime(12731): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #4: <item> tag requires a 'drawable' attribute or child tag defining a drawable
E/AndroidRuntime(12731): 	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:202)
E/AndroidRuntime(12731): 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:147)
E/AndroidRuntime(12731): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1150)
E/AndroidRuntime(12731): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1063)
E/AndroidRuntime(12731): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3736)
E/AndroidRuntime(12731): 	... 21 more
```

**Flutter doctor**
Copy and paste the output of `flutter doctor -v` here

```
>flutter doctor -v
[√] Flutter (Channel master, 1.24.0-8.0.pre.1, on Microsoft Windows [Version 10.0.19041.264], locale en-US)
    • Flutter version 1.24.0-8.0.pre.1 at C:\Users\m3\repos\flutter
    • Framework revision e444b1e3fa (5 weeks ago), 2020-10-30 00:41:52 -0400
    • Engine revision 99cc50dfff
    • Dart version 2.11.0 (build 2.11.0-266.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\m3\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • SM N900 (mobile) • 4d00b6ae472d80eb • android-arm    • Android 5.0 (API 21)
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 87.0.4280.66

• No issues found!

```

**To Reproduce**
1. Git checkout master branch
2. Open Android Studio
3. Connect your Android smartphone device to computer through USB port
4. Click the green triangle to build and run the app on the device
5. Error are thrown on terminal

**Expected behavior**
No error or exception is expected. The app should build and run fine on the device.

**Screenshots**

![image](https://user-images.githubusercontent.com/17475482/104844140-9b39a980-58e3-11eb-8fd4-fca72cbe64d3.png)

**Desktop information:**
 - OS: Windows 10
 - Browser Opera
 - Version:72.0.3815.400

**Smartphone information:**
 - Device: Samsung Galaxy Note 3
 - OS: Android 5.0
 - Browser Opera
 - Version 60.3.3004.55692

**Additional context**
Such posts show that maybe the Gradle build system needs to be configured differently, not sure:

https://stackoverflow.com/a/39419701/3405291

**Comment by Megidd** [comment]
### Pulling master branch

The exceptions is still thrown after pulling the most recent Flutter `master` branch:

```bash
m3@DESKTOP-QF5ESAN MINGW64 ~/repos/flutter (master)
$ git remote -v show
origin  https://github.com/flutter/flutter.git (fetch)
origin  https://github.com/flutter/flutter.git (push)

m3@DESKTOP-QF5ESAN MINGW64 ~/repos/flutter (master)
$ git pull origin master
```

Then, running Flutter `doctor`:

```bash
m3@DESKTOP-QF5ESAN MINGW64 ~/repos/flutter (master)
$ flutter doctor -v
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 609036f2bf7cae17a0b88c21fb3bdaff7159b713...
Building flutter tool...
Running pub upgrade...
Downloading package sky_engine...                                   3.9s
Downloading flutter_patched_sdk tools...                           50.9s
Downloading flutter_patched_sdk_product tools...                   51.7s
Downloading windows-x64 tools...                                  107.6s
Downloading windows-x64/font-subset tools...                       11.3s
[√] Flutter (Channel master, 1.26.0-2.0.pre.401, on Microsoft Windows [Version 10.0.19041.264], locale en-US)
    • Flutter version 1.26.0-2.0.pre.401 at C:\Users\m3\repos\flutter
    • Framework revision da5a454d5c (3 hours ago), 2021-01-17 01:24:03 -0500
    • Engine revision 609036f2bf
    • Dart version 2.12.0 (build 2.12.0-236.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\m3\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • SM N900 (mobile) • 4d00b6ae472d80eb • android-arm    • Android 5.0 (API 21)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

Flutter setup on Android Studio:

![image](https://user-images.githubusercontent.com/17475482/104844457-91b14100-58e5-11eb-9f8b-3c5d0fa84b62.png)

Dart setup on Android Studio:

![image](https://user-images.githubusercontent.com/17475482/104844470-9e359980-58e5-11eb-9b5b-84544290f21d.png)

**Comment by Megidd** [comment]
### Android 9 (API 28) is fine

I tested with with Samsung Galaxy A10 (SM A105F) with Android 9 (API 28) on it, the exception was *not* thrown. 

```bash
$ flutter doctor -v
[√] Flutter (Channel master, 1.26.0-2.0.pre.401, on Microsoft Windows [Version 10.0.19041.264], locale en-US)
    • Flutter version 1.26.0-2.0.pre.401 at C:\Users\m3\repos\flutter
    • Framework revision da5a454d5c (11 hours ago), 2021-01-17 01:24:03 -0500
    • Engine revision 609036f2bf
    • Dart version 2.12.0 (build 2.12.0-236.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\m3\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • SM A105F (mobile) • RF8M60PVD5F • android-arm    • Android 9 (API 28)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

### How to fix for Android 5.0 (API 21)

I just wanted to know how to resolve the exception for Android 5.0 (API 21)? I tried some suggestions here, but they didn't resolve the exception:

https://stackoverflow.com/a/39419701/3405291

**Comment by Megidd** [comment]
### Implication

Implication so far is that the app runs fine with Android 9 (API 28) but throws the above-mentioned exception with Android 5.0 (API 21). Does anybody know what could be the problem cause? How could I possibly run the app on Android 5.0 (API 21)?

**Comment by Megidd** [comment]
Commit cfa788a0b1c5556deabbfb149208a9586b6ee7e1 has added `android:resource="@drawable/launch_background"` statement to `android/app/src/main/AndroidManifest.xml` file. Commit is done by @Renzo-Olivares , so he might be able to comment on this. Thanks 😃

**Comment by Megidd** [comment]
My `android/app/src/main/res/drawable-v21/launch_background.xml` file contains:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Modify this file to customize your launch splash screen -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="?android:colorBackground" />

    <!-- You can insert your own image assets here -->
    <!-- <item>
        <bitmap
            android:gravity="center"
            android:src="@mipmap/launch_image" />
    </item> -->
</layer-list>
```

**Comment by Megidd** [comment]
My `android/app/src/main/AndroidManifest.xml` file contains:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="io.flutter.demo.gallery">

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:label="Home Shine"
        android:icon="@mipmap/launcher_icon">
        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme"
                />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
                android:name="io.flutter.embedding.android.SplashScreenDrawable"
                android:resource="@drawable/launch_background" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <!-- Don't delete the meta-data below.
                 This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
            <meta-data
                android:name="flutterEmbedding"
                android:value="2"/>
        </activity>
    </application>
</manifest>
```

**Comment by Megidd** [comment]
In file `android/app/src/main/AndroidManifest.xml`, the exception is resolved by commenting out this:

```xml
<meta-data
android:name="io.flutter.embedding.android.SplashScreenDrawable"
android:resource="@drawable/launch_background" />
```

Removing the above resolves the exception, although I'm not sure if it has any side effect.

**Comment by iamchathu** [comment]
I'm also getting this error for Play Store pre-test

Device specifications
Model name
P8 青春版
Manufacturer
Huawei
Android Version (SDK)
Android 5.0 (SDK 21)
Locale
en_US
Screen size
720 x 1280
Screen density (DPI)
320
RAM (total memory)
2,048 MB
OpenGL ES version
2.0
ABI
ARM64_V8
CPU
HiSilicon Hi6220

**Comment by arsan-official** [comment]
> In file `android/app/src/main/AndroidManifest.xml`, the exception is resolved by commenting out this:
> 
> ```
> <meta-data
> android:name="io.flutter.embedding.android.SplashScreenDrawable"
> android:resource="@drawable/launch_background" />
> ```
> 
> Removing the above resolves the exception, although I'm not sure if it has any side effect.

it's works ...

**Comment by kakzaki** [comment]
> 
> 
> My `android/app/src/main/res/drawable-v21/launch_background.xml` file contains:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> 
> <layer-list xmlns:android="http://schemas.android.com/apk/res/android">
>     <item android:drawable="?android:colorBackground" />
> 
>     
>     
> </layer-list>
> ```


you can change <item android:drawable="?android:colorBackground" /> to <item android:drawable="@android:color/white" />

**Comment by ferhadquluzade** [comment]
> In file `android/app/src/main/AndroidManifest.xml`, the exception is resolved by commenting out this:
> 
> ```
> <meta-data
> android:name="io.flutter.embedding.android.SplashScreenDrawable"
> android:resource="@drawable/launch_background" />
> ```
> 
> Removing the above resolves the exception, although I'm not sure if it has any side effect.

hi thanks it worked

**Comment by caveligh** [comment]
> > My `android/app/src/main/res/drawable-v21/launch_background.xml` file contains:
> > ```
> > <?xml version="1.0" encoding="utf-8"?>
> > 
> > <layer-list xmlns:android="http://schemas.android.com/apk/res/android">
> >     <item android:drawable="?android:colorBackground" />
> > 
> >     
> >     
> > </layer-list>
> > ```
> 
> you can change item android:drawable="?android:colorBackground" to item android:drawable="@android:color/white"

it's works ... Thanks

**Comment by chaudharydeepanshu** [comment]
This issue is due to the fact that the bitmap tag in launch_background doesn't support xml files which was being used for adaptive icon in android so replace launch_background.xml code in drawable:
from this
```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:drawable="@color/gray"/>
    <item>
        <bitmap
            android:gravity="center"
            android:src="@mipmap/ic_launcher"/>
    </item>
</layer-list>
```
to this
```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:drawable="@color/gray"/>
    <item
        android:drawable="@mipmap/ic_launcher_round"
        android:gravity="center"/>
</layer-list>
```

This will work for the splash screen now.

credits: [this blog post](https://bignerdranch.com/blog/splash-screens-the-right-way/)
