### ISSUE TITLE
cannot build successfully on iPhone 11

### ISSUE THREAD

**Issue by mfch101** [flutter/gallery#416]
I worked on MacOS 11.4.6, with the IDE of vscode, and I want build the code running on ios emulator of IPhone 11 Pro Max.
I have Execute the commands ：

lutter channel master
flutter upgrade
flutter channel stable
flutter upgrade
flutter config --enable-ios
flutter create .

and then ,I execute the command :
flutter run

but it failed , the results are as follow:

"af": 11 untranslated message(s).
"am": 11 untranslated message(s).
"ar": 11 untranslated message(s).
"ar_EG": 11 untranslated message(s).
"ar_JO": 11 untranslated message(s).
"ar_MA": 11 untranslated message(s).
"ar_SA": 11 untranslated message(s).
"as": 11 untranslated message(s).
"az": 11 untranslated message(s).
"be": 11 untranslated message(s).
"bg": 11 untranslated message(s).
"bn": 11 untranslated message(s).
"bs": 11 untranslated message(s).
"ca": 11 untranslated message(s).
"cs": 11 untranslated message(s).
"da": 11 untranslated message(s).
"de": 11 untranslated message(s).
"de_AT": 11 untranslated message(s).
"de_CH": 11 untranslated message(s).
"el": 11 untranslated message(s).
"en_AU": 11 untranslated message(s).
"en_CA": 11 untranslated message(s).
"en_GB": 11 untranslated message(s).
"en_IE": 11 untranslated message(s).
"en_IN": 11 untranslated message(s).
"en_NZ": 11 untranslated message(s).
"en_SG": 11 untranslated message(s).
"en_ZA": 11 untranslated message(s).
"es": 11 untranslated message(s).
"es_419": 11 untranslated message(s).
"es_AR": 11 untranslated message(s).
"es_BO": 11 untranslated message(s).
"es_CL": 11 untranslated message(s).
"es_CO": 11 untranslated message(s).
"es_CR": 11 untranslated message(s).
"es_DO": 11 untranslated message(s).
"es_EC": 11 untranslated message(s).
"es_GT": 11 untranslated message(s).
"es_HN": 11 untranslated message(s).
"es_MX": 11 untranslated message(s).
"es_NI": 11 untranslated message(s).
"es_PA": 11 untranslated message(s).
"es_PE": 11 untranslated message(s).
"es_PR": 11 untranslated message(s).
"es_PY": 11 untranslated message(s).
"es_SV": 11 untranslated message(s).
"es_US": 11 untranslated message(s).
"es_UY": 11 untranslated message(s).
"es_VE": 11 untranslated message(s).
"et": 11 untranslated message(s).
"eu": 11 untranslated message(s).
"fa": 11 untranslated message(s).
"fi": 11 untranslated message(s).
"fil": 11 untranslated message(s).
"fr": 11 untranslated message(s).
"fr_CA": 11 untranslated message(s).
"fr_CH": 11 untranslated message(s).
"gl": 11 untranslated message(s).
"gsw": 11 untranslated message(s).
"gu": 11 untranslated message(s).
"he": 11 untranslated message(s).
"hi": 11 untranslated message(s).
"hr": 11 untranslated message(s).
"hu": 11 untranslated message(s).
"hy": 11 untranslated message(s).
"id": 11 untranslated message(s).
"is": 11 untranslated message(s).
"it": 11 untranslated message(s).
"ja": 11 untranslated message(s).
"ka": 11 untranslated message(s).
"kk": 11 untranslated message(s).
"km": 11 untranslated message(s).
"kn": 11 untranslated message(s).
"ko": 11 untranslated message(s).
"ky": 11 untranslated message(s).
"lo": 11 untranslated message(s).
"lt": 11 untranslated message(s).
"lv": 11 untranslated message(s).
"mk": 11 untranslated message(s).
"ml": 11 untranslated message(s).
"mn": 11 untranslated message(s).
"mr": 11 untranslated message(s).
"ms": 11 untranslated message(s).
"my": 11 untranslated message(s).
"nb": 11 untranslated message(s).
"ne": 11 untranslated message(s).
"nl": 11 untranslated message(s).
"or": 11 untranslated message(s).
"pa": 11 untranslated message(s).
"pl": 11 untranslated message(s).
"pt": 11 untranslated message(s).
"pt_BR": 11 untranslated message(s).
"pt_PT": 11 untranslated message(s).
"ro": 11 untranslated message(s).
"ru": 11 untranslated message(s).
"si": 11 untranslated message(s).
"sk": 11 untranslated message(s).
"sl": 11 untranslated message(s).
"sq": 11 untranslated message(s).
"sr": 11 untranslated message(s).
"sr_Latn": 11 untranslated message(s).
"sv": 11 untranslated message(s).
"sw": 11 untranslated message(s).
"ta": 11 untranslated message(s).
"te": 11 untranslated message(s).
"th": 11 untranslated message(s).
"tl": 11 untranslated message(s).
"tr": 11 untranslated message(s).
"uk": 11 untranslated message(s).
"ur": 11 untranslated message(s).
"uz": 11 untranslated message(s).
"vi": 11 untranslated message(s).
"zh": 11 untranslated message(s).
"zh_CN": 11 untranslated message(s).
"zh_HK": 11 untranslated message(s).
"zh_TW": 11 untranslated message(s).
"zu": 11 untranslated message(s).
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 

This will generate a JSON format file containing all messages that 
need to be translated.
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...                                           1,086ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      - Flutter
      - package_info
      - path_provider
      - url_launcher

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update

    Comparing resolved specification to the sandbox manifest
      A Flutter
      A package_info
      A path_provider
      A url_launcher

    Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing package_info (0.0.1)

    -> Installing path_provider (0.0.1)

    -> Installing url_launcher (0.0.1)
      - Running pre install hooks

    Generating Pods project
      - Creating Pods project
      - Installing files into Pods project
        - Adding source files
        - Adding frameworks
        - Adding libraries
        - Adding resources
        - Adding development pod helper files
        - Linking headers
      - Installing Pod Targets
        - Installing target `Flutter` iOS 8.0
        - Installing target `package_info` iOS 8.0
          - Generating module map file at `Pods/Target Support Files/package_info/package_info.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/package_info/package_info-umbrella.h`
          - Generating Info.plist file at `Pods/Target Support Files/package_info/package_info-Info.plist`
          - Generating dummy source at `Pods/Target Support Files/package_info/package_info-dummy.m`
        - Installing target `path_provider` iOS 8.0
          - Generating module map file at `Pods/Target Support Files/path_provider/path_provider.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/path_provider/path_provider-umbrella.h`
          - Generating Info.plist file at `Pods/Target Support Files/path_provider/path_provider-Info.plist`
          - Generating dummy source at `Pods/Target Support Files/path_provider/path_provider-dummy.m`
        - Installing target `url_launcher` iOS 8.0
          - Generating module map file at `Pods/Target Support Files/url_launcher/url_launcher.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/url_launcher/url_launcher-umbrella.h`
          - Generating Info.plist file at `Pods/Target Support Files/url_launcher/url_launcher-Info.plist`
          - Generating dummy source at `Pods/Target Support Files/url_launcher/url_launcher-dummy.m`
      - Installing Aggregate Targets
        - Installing target `Pods-Runner` iOS 11.0
          - Generating Info.plist file at `Pods/Target Support Files/Pods-Runner/Pods-Runner-Info.plist`
          - Generating module map file at `Pods/Target Support Files/Pods-Runner/Pods-Runner.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/Pods-Runner/Pods-Runner-umbrella.h`
          - Generating dummy source at `Pods/Target Support Files/Pods-Runner/Pods-Runner-dummy.m`
      - Generating deterministic UUIDs
      - Stabilizing target UUIDs
      - Running post install hooks
    [!] An error occurred while processing the post-install hook of the Podfile.

    undefined method `each_child' for #<Dir:0x00007fed820d7948>
    Did you mean?  each_slice

    /Users/mfch/flutter/packages/flutter_tools/bin/podhelper.rb:54:in `block in flutter_additional_ios_build_settings'
    /Users/mfch/flutter/packages/flutter_tools/bin/podhelper.rb:51:in `each'
    /Users/mfch/flutter/packages/flutter_tools/bin/podhelper.rb:51:in `flutter_additional_ios_build_settings'
    /Users/mfch/work/flutter/gallery/ios/Podfile:39:in `block (3 levels) in from_ruby'
    /Users/mfch/work/flutter/gallery/ios/Podfile:38:in `each'
    /Users/mfch/work/flutter/gallery/ios/Podfile:38:in `block (2 levels) in from_ruby'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:897:in `run_podfile_post_install_hook'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:885:in `block in run_podfile_post_install_hooks'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:884:in `run_podfile_post_install_hooks'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:329:in `block (2 levels) in create_and_save_projects'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:328:in `block in create_and_save_projects'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:299:in `generate_pods_project'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:178:in `integrate'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:166:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:899:in `rescue in run_podfile_post_install_hook'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:896:in `run_podfile_post_install_hook'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:885:in `block in run_podfile_post_install_hooks'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:884:in `run_podfile_post_install_hooks'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:329:in `block (2 levels) in create_and_save_projects'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:328:in `block in create_and_save_projects'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:299:in `generate_pods_project'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:178:in `integrate'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:166:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error running pod install
Error launching application on iPhone 11 Pro Max.

**Comment by mfch101** [comment]
I have solved the problem.

the solution:

The method Dir.each_child was introduced in Ruby 2.5, but I am using Ruby 2.3.0.
I updated Ruby to 2.7.2    (  2.5 or later is OK)
After Ruby updating , restart the IDE and re-install cocoapods.

**Comment by mfch101** [comment]
I have solved the problem.

the solution:

The method Dir.each_child was introduced in Ruby 2.5, but I am using Ruby 2.3.0.
I updated Ruby to 2.7.2 ( 2.5 or later is OK)
After Ruby updating , restart the IDE and re-install cocoapods.
