### ISSUE TITLE
Not working black screen

### ISSUE THREAD

**Issue by fede1295** [flutter/gallery#500]
For me this project not working with flutter web.. 
Always the same errors:
- Black Screen
- Finished with error: HttpException: Content size below specified contentLength.  0 bytes written but expected 1225., uri = /main_module.bootstrap.js

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.3.0-2.0.pre.206, on Ubuntu 20.04.1 LTS 5.4.0-73-generic, locale en_US.utf8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
[✓] Connected device (1 available)

**Comment by guidezpl** [comment]
Is there a longer stack trace associated with that error?

**Comment by fede1295** [comment]
[  +72 ms] DwdsInjector: Received request for entrypoint at http://localhost:38105/main_module.bootstrap.js
[        ] MetadataProvider: Loading debug metadata...
[   +6 ms] MetadataProvider: Loaded debug metadata (no sound null safety)
[   +2 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:38105/main_module.bootstrap.js
Finished with error: HttpException: Content size below specified contentLength.  0 bytes written but expected 1225., uri = /main_module.bootstrap.js
[  +13 ms] DwdsInjector: Received request for entrypoint at http://localhost:38105/main_module.bootstrap.js
[        ] MetadataProvider: Loading debug metadata...
[   +9 ms] MetadataProvider: Loaded debug metadata (no sound null safety)
[   +4 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:38105/main_module.bootstrap.js
[   +7 ms] DwdsInjector: Received request for entrypoint at http://localhost:38105/main_module.bootstrap.js
[        ] MetadataProvider: Loading debug metadata...
[   +6 ms] MetadataProvider: Loaded debug metadata (no sound null safety)
[   +2 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:38105/main_module.bootstrap.js
[  +22 ms] DevHandler: Stopped debug service on ws://127.0.0.1:43491

[  +37 ms] "flutter run" took 51,370ms.
[   +2 ms] Failed to clean up temp directory: /tmp/flutter_tools.ACUDSO/flutter_tools.AMEDCG
[        ] Failed to clean up temp directory: /tmp/flutter_tools.ACUDSO/flutter_tools.AMEDCG
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:564:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1090:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

**Comment by guidezpl** [comment]
Hmm I'm going to transfer this issue to flutter/flutter for help
